// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: conversations.sql

package db

import (
	"context"
)

const addConversationMember = `-- name: AddConversationMember :exec
INSERT INTO conversation_members (
    conversation_id,
    user_id
)
VALUES (?, ?)
`

type AddConversationMemberParams struct {
	ConversationID string
	UserID         string
}

func (q *Queries) AddConversationMember(ctx context.Context, arg AddConversationMemberParams) error {
	_, err := q.db.ExecContext(ctx, addConversationMember, arg.ConversationID, arg.UserID)
	return err
}

const createConversation = `-- name: CreateConversation :exec
INSERT INTO conversations (
    id
)
VALUES (?)
`

func (q *Queries) CreateConversation(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, createConversation, id)
	return err
}

const findDirectConversation = `-- name: FindDirectConversation :one
SELECT
    cm1.conversation_id
FROM conversation_members cm1
JOIN conversation_members cm2
    ON cm1.conversation_id = cm2.conversation_id
WHERE cm1.user_id = ?
    AND cm2.user_id = ?
LIMIT 1
`

type FindDirectConversationParams struct {
	UserID   string
	UserID_2 string
}

func (q *Queries) FindDirectConversation(ctx context.Context, arg FindDirectConversationParams) (string, error) {
	row := q.db.QueryRowContext(ctx, findDirectConversation, arg.UserID, arg.UserID_2)
	var conversation_id string
	err := row.Scan(&conversation_id)
	return conversation_id, err
}

const getConversationByID = `-- name: GetConversationByID :one
SELECT
    id,
    created_at
FROM conversations
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetConversationByID(ctx context.Context, id string) (Conversation, error) {
	row := q.db.QueryRowContext(ctx, getConversationByID, id)
	var i Conversation
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}
