// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: conversations.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const addConversationMember = `-- name: AddConversationMember :exec
INSERT INTO conversation_members (
    conversation_id,
    user_id
)
VALUES (?, ?)
`

type AddConversationMemberParams struct {
	ConversationID string
	UserID         string
}

func (q *Queries) AddConversationMember(ctx context.Context, arg AddConversationMemberParams) error {
	_, err := q.db.ExecContext(ctx, addConversationMember, arg.ConversationID, arg.UserID)
	return err
}

const createConversation = `-- name: CreateConversation :exec
INSERT INTO conversations (
    id,
    user_low,
    user_high
)
VALUES (?, ?, ?)
`

type CreateConversationParams struct {
	ID       string
	UserLow  sql.NullString
	UserHigh sql.NullString
}

func (q *Queries) CreateConversation(ctx context.Context, arg CreateConversationParams) error {
	_, err := q.db.ExecContext(ctx, createConversation, arg.ID, arg.UserLow, arg.UserHigh)
	return err
}

const findDirectConversation = `-- name: FindDirectConversation :one
SELECT id
FROM conversations
WHERE user_low = ?
  AND user_high = ?
LIMIT 1
`

type FindDirectConversationParams struct {
	UserLow  sql.NullString
	UserHigh sql.NullString
}

func (q *Queries) FindDirectConversation(ctx context.Context, arg FindDirectConversationParams) (string, error) {
	row := q.db.QueryRowContext(ctx, findDirectConversation, arg.UserLow, arg.UserHigh)
	var id string
	err := row.Scan(&id)
	return id, err
}

const getConversationByID = `-- name: GetConversationByID :one
SELECT
    id,
    created_at
FROM conversations
WHERE id = ?
LIMIT 1
`

type GetConversationByIDRow struct {
	ID        string
	CreatedAt time.Time
}

func (q *Queries) GetConversationByID(ctx context.Context, id string) (GetConversationByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getConversationByID, id)
	var i GetConversationByIDRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const listDirectConversationsForUser = `-- name: ListDirectConversationsForUser :many
SELECT
    c.id,
    c.created_at,
    u.id AS other_user_id,
    u.username AS other_username
FROM conversations c
JOIN conversation_members cm
    ON cm.conversation_id = c.id
JOIN conversation_members other_cm
    ON other_cm.conversation_id = c.id
JOIN users u
    ON u.id = other_cm.user_id
WHERE cm.user_id = ?
  AND other_cm.user_id != ?
  AND c.user_low IS NOT NULL
  AND c.user_high IS NOT NULL
ORDER BY c.created_at DESC
`

type ListDirectConversationsForUserParams struct {
	UserID   string
	UserID_2 string
}

type ListDirectConversationsForUserRow struct {
	ID            string
	CreatedAt     time.Time
	OtherUserID   string
	OtherUsername string
}

func (q *Queries) ListDirectConversationsForUser(ctx context.Context, arg ListDirectConversationsForUserParams) ([]ListDirectConversationsForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listDirectConversationsForUser, arg.UserID, arg.UserID_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDirectConversationsForUserRow
	for rows.Next() {
		var i ListDirectConversationsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.OtherUserID,
			&i.OtherUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
