// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: messages.sql

package db

import (
	"context"
	"time"
)

const createMessage = `-- name: CreateMessage :exec
INSERT INTO messages (
    id,
    conversation_id,
    sender_id,
    content
)
VALUES (?, ?, ?, ?)
`

type CreateMessageParams struct {
	ID             string
	ConversationID string
	SenderID       string
	Content        string
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) error {
	_, err := q.db.ExecContext(ctx, createMessage,
		arg.ID,
		arg.ConversationID,
		arg.SenderID,
		arg.Content,
	)
	return err
}

const getMessageByID = `-- name: GetMessageByID :one
SELECT
    id,
    conversation_id,
    sender_id,
    content,
    created_at
FROM messages
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetMessageByID(ctx context.Context, id string) (Message, error) {
	row := q.db.QueryRowContext(ctx, getMessageByID, id)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.SenderID,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const listMessages = `-- name: ListMessages :many
SELECT
    id,
    conversation_id,
    sender_id,
    content,
    created_at
FROM messages
WHERE conversation_id = ?
ORDER BY created_at DESC, id DESC
LIMIT ?
`

type ListMessagesParams struct {
	ConversationID string
	Limit          int32
}

func (q *Queries) ListMessages(ctx context.Context, arg ListMessagesParams) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, listMessages, arg.ConversationID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.SenderID,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessagesBefore = `-- name: ListMessagesBefore :many
SELECT
    id,
    conversation_id,
    sender_id,
    content,
    created_at
FROM messages
WHERE conversation_id = ?
  AND (
      created_at < ?
      OR (
          created_at = ?
          AND id < ?
      )
  )
ORDER BY created_at DESC, id DESC
LIMIT ?
`

type ListMessagesBeforeParams struct {
	ConversationID string
	CreatedAt      time.Time
	CreatedAt_2    time.Time
	ID             string
	Limit          int32
}

func (q *Queries) ListMessagesBefore(ctx context.Context, arg ListMessagesBeforeParams) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, listMessagesBefore,
		arg.ConversationID,
		arg.CreatedAt,
		arg.CreatedAt_2,
		arg.ID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.SenderID,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
