// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"
)

type Conversation struct {
	ID        string
	CreatedAt time.Time
}

type ConversationMember struct {
	ConversationID string
	UserID         string
}

type Message struct {
	ID             string
	ConversationID string
	SenderID       string
	Content        string
	CreatedAt      time.Time
}

type User struct {
	ID           string
	Username     string
	Email        string
	PasswordHash string
	CreatedAt    time.Time
}
